### PR TITLE
black belt request - basil

### PR DESCRIPTION
**Pull request by michael-basil**
**Authenticity When It Matters Most: Four Principles for Transformative Living,  Leadership and Parenting**

Working in the Mindset Dojo for the past several years has been an incredibly rewarding and uniquely distinctive experience. The Mindset Dojo began with my work at SAP, but my current reflection is part of my Black Belt submission claim for the public Mindset Dojo, a program I have been deeply engaged with for the last several months.

Through this journey, I’ve come to understand that the core mission of the Mindset Dojo is to help us *become fully authentic when it matters most*. Many people talk about authenticity—showing up as our authentic or true selves—but what we focus on in the Dojo is cultivating the ability to remain authentic in life’s most challenging and critical moments when emotions are really flaring up. This is often when most people lose their way.

At the Black Level of the program, we focus on embodying four key principles. These principles act as a compass, guiding us toward transformative living. In this article, I will reflect on how my experiences have transformed and then explore each principle, sharing how they have surfaced in my own journey, highlighting results that have unfolded along the way.

**Transformations in Experience:** 

Reflecting over the past several years and the last few months in particular, the following list of transformation progressions is what comes up for me.

(I will not go into depth on the narratives of these in this article, but I am happy to unpack in conversation for those who are interested.  However, of greater interest is to hear the stories about how others have experienced the same AND OR if they find themselves in a cycle unable to progress.)

I have experienced each of these individually; observed these with family, friends and colleagues; as well as have been part of the progression within corporate teams and departments.

* From Burnout to Breakthrough  
* From People-Pleasing to Purposeful-Action  
* From Irritated Isolation to Interconnected Innovation  
* From Anxiety & Depression to Discernment & Agency  
* From Scared & Conflicted to Curious & Strategic  
* From Acquisition to Appreciation  
* From Failure to Discovery

Increasing Authenticity in:

* Self-expression  
* Conversations  
* Relationships  
* Families  
* Leadership  
* Teams  
* Cultures  
* Transitions

Some of the transformation phases were relatively short as in weeks, others unpacked in levels and layers over a long period of time spanning months and years.  The constant is to keep working with situations where they are at, playing the ball where it lies so to speak.  

It strikes me that the practical work with Mindset Dojo has been an integral part of clearing the self-imposed limitation allowing new pathways to reveal themselves.  How? You may ask.  

### **Principle 1: Relax and Reconnect  with Purpose Under Pressure**

The first principle is to *reconnect with purpose under pressure*.This might sound simple, but how can you reconnect with purpose if you're not clear on what your purpose actually is? The level of transformation you aim for will be shaped by the clarity of your vision. If you're truly striving for a life-changing result, it often requires deep soul-searching and valuable introspection to uncover your true purpose.

Let me share a recent experience that illustrates this principle in a simple, real-world scenario. In a conversation with a friend, I found myself feeling attacked. My ego was on the defensive, though at the time I wasn’t fully conscious of this pattern playing out initially. Then, suddenly, I had a moment of realization—*Is this how I want to show up in this conversation?* I recognized that what I was doing didn’t feel authentic.

At that moment, I turned to the compass of the Four Principles. The first principle came to mind: *Reconnect with purpose.* I realized that I had lost sight of my purpose. Instead of engaging in an authentic exchange, I was focused on defending my self-image. My ego felt judged, and in response, I was resisting and counter attacking. It became a back-and-forth of judgments and defenses. But then I asked myself, *What is my real purpose here?* I want to have authentic conversations, and this didn’t feel like one.

So with the principle in mind I let go of the need to defend myself and employed some of the strategies I’ve learned through the Mindset Dojo. I decided to really listen—without judgment. Even though my friend’s tone seemed judgmental, I chose not to judge what I was hearing as wrong for being that way. It wasn’t easy at the moment, but I stayed the course.

As the conversation unfolded, I reflected on what was being said and paraphrased it back, making sure to capture my friend’s key points, including and especially the ones I disagreed with so that he felt heard, and his emotions were validated. (I should note that I didn’t internalize the judgment I was experiencing and the disagreeable points as truth, rather true from his perspective.)  When I heard “That’s right” in response, the energy shifted. My friend was surprised by how the conversation had evolved. What had started as a fight now became something more playful, maybe even like a dance. We moved from confrontation to connection.  

This shift from self-defense to shared purpose changed everything. The tension dissolved, and what emerged was a meaningful, authentic connection. Instead of focusing on myself, I began focusing on *it*—the purpose. We stopped trying to control each other, and instead, we extended the conversation in a way that created harmony.

In this moment, the energy, the dynamics, and the metaphor of the interaction all shifted. But this transformation wouldn’t have been possible without the first principle: *reconnecting with purpose*. It’s this internal reflection—this reconnection—that shifts us out of a reactive, defensive mode and into a higher state of being. Our heart opens, our gut calms, and we become aligned with our authentic self. In this alignment, our presence becomes clearer, and we can show up in the world as our true selves.

### **Principle 2: Emotional  Wisdom is Trusting Your Compass When Encountering  Deep Waves**

The second principle is *emotional wisdom*, which is about trusting your compass when encountering deep emotional waves. This is an interesting shift from the first principle, but before we dive into it, let's clarify: *What is the compass?* Well, depending on your objective, the compass varies.  However, depending on your objective or transformational vision, your compass may vary. If you're focused on business success, for example, you might use success principles as your guide. But for the sake of this discussion, we’ll stick with the compass rooted in the Mindset Dojo Four Principles.

Let’s start by acknowledging that encountering deep emotional waves—especially negative ones—can be overwhelming. In those moments, our instinctual responses often kick in. However, the key is developing the reflex to discern between discomfort and actual danger. For authenticity to emerge, we must sometimes enter zones of discomfort.

A simple, yet powerful, example comes from watching my children, especially my son Jack. When he was first learning to fold a blanket, he faced what felt like a big, negative wave of frustration. It’s not unlike how we feel when we face something new and challenging. But with support and persistence, he kept going. Over time, each attempt became easier, the wave dampened, and he eventually mastered the task. He was so proud of his progress that he eventually taught his little sister, Lila. This pattern has played out multiple times in our family, whether at home or on the Aikido mat, where my children and I are early students. It highlights how emotional wisdom can be cultivated over time, by leaning into discomfort.  We are at the beginning stages, but it seems like we are on a good path\!

However, it’s always trickier when we’re in the eye of the storm ourselves. Recently, I faced a tricky business decision, and it brought a lot of inner tension. I became aware that I was in the middle of a deep emotional wave, and that’s when this principle came to mind. I took a step back in my mind, which allowed me to access my higher mind and recall my purpose.

In this scenario, I had three options in front of me—one of which came with significant time pressure. The other two didn’t, so I carefully considered which path felt the most authentic, which can be slippery at the moment as ego is tricky\! As I reflected, I realized by tuning into my heart that pursuing the time-pressured option would have been a shortcut—a potential compromise of my deeper values. Even though the outcome might have been successful, it wouldn’t have aligned with my authentic purpose and likely would be short lived. So, I let it go. 

Initially, letting that option pass didn’t feel great, quite the opposite. I was still in the emotional storm. But soon after, things started to open up, and I experienced a shift. The tension transformed into creative clarity, and I was able to harvest valuable insights from the situation. This is a pattern I’ve noticed in myself: when I lean into discomfort, trust my compass, and stay aligned with my true self, emotional storms often lead to creative clarity.  For me this was a breakthrough moment.

This principle is about more than just regulating emotions—it’s about staying grounded. Without alignment to our deeper values and principles it’s easy to lose our way in pursuit of results that may not serve us. Emotional wisdom, in this sense, keeps us expanding our comfort zone in an authentic way. It ensures we grow in alignment with who we truly are, rather than expanding in ways that don’t resonate with our deeper purpose and cause us to become disoriented and go in negative circles fueled by a self-preservation seeking and attachment clutching self-concept (ego).

### **Principle 3: Conflict Reveals  Insight That Deepens Even Adversarial  Relationships**

This principle is perhaps the most transformative of all: *Conflict reveals insight that deepens even adversarial relationships.* It’s a critical concept to grasp because, in many environments—whether among family, friends, or colleagues—people tend to be either averse to, frozen by, or aggressive with conflict. We see it play out in various dynamics all around us. For me, this principle has been a game-changer, particularly in professional settings.

When I was at SAP, early on this principle began to realign my approach to conversations, especially in situations where conflict arose. It allowed for discussions that ventured far beyond the usual realms of possibility and comfort, opening the door to new visions. A phrase from one of the dojo executive sponsors comes to mind: *“Get comfortable being uncomfortable.”* Over time, this principle has evolved for me. Initially, it felt more externally focused—conflict as confrontation to stir things up. Now, it’s become more of an inward reflection, where conflict is teaching me something about myself.

If we feel tension inside due to conflict, it’s an indicator that there’s something important to learn. And this holds true even in adversarial relationships. In my professional life, this principle was a catalyst for many successful negotiations, enabling conversations that transformed tense team dynamics. But perhaps the most transcendent application of this principle in my life was during a high-conflict divorce.

At that time, many people—family, attorneys—doubted that it was possible to move from such high conflict to a healthy co-parenting relationship. I set a transformational vision: to find a way for my former spouse and I to co-parent in a healthy way. It seemed unfathomable to those around us. Multiple attorneys and even my family were skeptical. They might say otherwise now, but at the time, their belief in this vision was lacking.  They said my former spouse would never change. They were unclear that the transformation vision wasn’t to change her, but for me to learn what I could do for and within myself to positively influence the situation.  Find and dissolve fixed mindsets and limiting beliefs in my own way of being.  My hypothesis was that I influenced the existence of this situation, so I can influence an alternative to the situation.

With purposeful determination, I began applying these grounding principles. One conversation at a time, I worked through the conflict, learning from it and seeking insights along the way, reflecting on the way out of encounters. Through the divorce proceedings, the landscape transformed. Looking back now, even my former spouse might acknowledge the profound shift that took place. What’s most impactful is the influence this has had on our children, not just in the short but also the long term.

In a corporate setting, conflict between departments can disrupt productivity. But in this personal context, the stakes were much higher—our children were watching. Aware or not, they witnessed the difference between parents embroiled in conflict and parents who found a way to co-parent without constant litigation and defensive barriers, through safe and healthy buffering.

Through this process, I realized that learning from conflict isn’t just about resolving external disagreements; it’s about deepening our understanding of ourselves and others. As a parent, I often joke that my children and even my former spouse have arrived in my life to teach me about the insights that come through conflict. I still have much to learn, and this principle shows me that.

The real power of this principle is that it lights up an authenticity option set no matter how far you may have hit the ball far into the woods on life’s golf course. Once you understand that conflict reveals insight, you can begin to embrace and embody it, even in seemingly adversarial relationships. This realization leads to breakthroughs, whether in negotiations, parenting, or personal growth. It’s not just about getting comfortable with discomfort—it’s about appreciating, embracing, and embodying the truth that conflict is a source of wisdom, especially about yourself.

### **Principle 4: Reflex Improves Through  Intentional Reflective Repetition**

The fourth principle is: *Reflex improves through intentional reflective repetition*. This principle highlights a major differentiator of the Mindset Dojo and has been particularly transformative for me over the past few  years. As I began practicing Aikido with my children, and incorporated daily meditation into my routine, the importance of repetition became increasingly clear. While this principle had always been present in the Dojo, it didn’t fully crystallize until I embraced these pursuits.

It became obvious that whatever we’re learning needs to be pressure-tested. Just as we develop muscle memory on the Aikido mat, we also need to create new pathways in what I call the *Full Mind*—the head, heart, and gut. If we want to foster emotional wisdom and healthier approaches to conflict, we must repeatedly practice new ways of responding until they become second nature.

Mike Tyson once said: *“Everybody has a plan until they’re punched in the mouth.”* What Tyson doesn’t say, though, is that over time, with intentional reflection and preparation, your reflexes improve. Eventually, your plan and how you respond in the heat of the moment begin to align. With practice, you may reach a point where you can avoid that punch entirely. Similarly, as your ego becomes more flexible, less rigid, and less reactive, you’re able to adapt more fluidly to the pressures of life. You may even embody the Bruce Lee saying, *“Be like water,”* flowing effortlessly rather than resisting like a fixed oak tree.

What makes the Mindset Dojo unique is that we engage in *conversational repetition* as a key part of our practice. Our program focuses on three types of intentional practice: solo reflection, partner dialogues where we explore concepts and movements, and group circle conversations. As we progress through the different levels of the Dojo, we write reflections, like the one you’re reading now as part of my Black Level submission. We also engage in one-on-one conversations with the sensei, and together, we pressure-test the principles, practices, tools, and strategies we’ve been working on.

These group circles provide a powerful space to test our reflexes. In these settings, we observe how smoothly we can recall the principles as opportunities organically emerge.  For example, we can gauge how well we pause and take dynamic silence using techniques from [*Never Split the Difference by Chris Voss*](https://www.youtube.com/watch?v=MjhDkNmtjy0), and how effectively we shift energy using techniques like the [*Zen Leader Essential Flips by Ginny Whitelaw Roshi*](https://www.youtube.com/watch?v=TsnVMJ7_DqA). It’s here that we determine whether these concepts are truly embodied, whether they feel authentic in our discussions and how they show up in our lives.

In the Dojo, we expand our comfort zones through these authentic, safe, conversational settings. We intentionally enter zones of discomfort with the support of others who are also reconciling their own transformative visions. Just like in meditation, where at the end someone might ring a bell and remind us to *“take the practice with you,”* we aim to carry the lessons of reflective repetition into our daily lives.

**Authenticity Switch Revealed**

Whether it’s on the Aikido mat or in our relationships with colleagues, friends, or family members, this approach helps smooth out inauthentic actions. Over time, the repetition creates alignment between our head, heart, and gut as a reflex. When this alignment happens, our presence becomes truly authentic, showing in our energy when we have conversations with people and in our actions over time that we and others, aware or not, use as a key input in how they view and learn to trust our intentions.

Thank you for the space to allow me to share this with and what I’ve learned on this journey: *to become fully authentic when it matters most*. At this level and stage, I strive to continue to practice, as well as help others in similar pursuit. This approach—grounded in the embodiment of the Four Principles—creates an *Authenticity Switch* in our own mind which influences not only our own experience, but those we are encircled with.

### CODE REVIEW

**Comment by michael-basil** [comment]
@anuolu @abkaufmann @fzuill @aphor @billwestfall @jimmanzzullo 

Please find above my black belt claim.

I have pressure tested this with each of you and several people outside of the community.

One notable person is Alfred Darby.  Another is a writing coach.   

I feel that all the criteria has been met in spirit, though am happy to have a discussion at the next circle meeting (not this Friday, but after that).

Michael Basil 🌿

**Review by billwestfall — COMMENTED** [review]
+1, comprehensive reflection. It's interesting how you are on a path wildly different than mine but you can communicate clearly where you are, like a well drawn map

**Review by billwestfall — APPROVED** [review]
+1

**Review by abkaufmann — APPROVED** [review]
Request reviewed and approved!

**Pull request merged**
